version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: auth-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/database.db:/app/database.db
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: auth-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped